apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmosreplication.fullname" . }}-estimator
  labels:
    {{- include "cosmosreplication-estimator.labels" . | nindent 4 }}
data:
{{- $replicationHostReadyUrl := printf "http://%s:%s/healthz/ready" (include "cosmosreplication.fullname" .) (toString .Values.service.port) }}
{{- $replicationHost := dict "ReplicationHost" (dict "ReadyUrl" $replicationHostReadyUrl "ReadyTimeout" 60) }}
{{- $appSettings := mustMergeOverwrite .Values.appSettings $replicationHost .Values.estimator.appSettings }}
  appsettings.json: |
    {{- $appSettings | toPrettyJson | nindent 4 }}
