apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cosmosreplication.fullname" . }}
  labels:
    {{- include "cosmosreplication.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {{- .Values.appSettings | toPrettyJson | nindent 4 }}
