apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmosreplication.fullname" . }}-estimator
  labels:
    {{- include "cosmosreplication-estimator.labels" . | nindent 4 }}
spec:
  {{- with .Values.estimator.service | default .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "cosmosreplication-estimator.selectorLabels" . | nindent 4 }}
