name: Build

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Git Fetch Tags"
        run: git fetch --tags
      - name: "Install .NET"
        uses: actions/setup-dotnet@v4
      - name: Dotnet Restore
        run: dotnet restore
      - name: Dotnet Format
        run: dotnet format --verify-no-changes --severity info
      - name: Dotnet Build
        run: dotnet build -c Release --no-restore
      # - name: Test
      #   run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:Threshold=75 /p:CoverletOutput="../../artifacts/"
      - name: Dotnet Pack
        run: dotnet pack -c Release --no-build --include-symbols --include-source -p:SymbolPackageFormat=snupkg -o ./artifacts
      - name: Dotnet Publish
        run: dotnet publish -c Release
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build of CosmosReplication.Host.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CosmosReplication.Host.Dockerfile
          push: false
          platforms: linux/amd64
      - name: Docker Build of CosmosReplication.Estimator.Host.Dockerfile
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CosmosReplication.Estimator.Host.Dockerfile
          push: false
          platforms: linux/amd64
      - name: "Upload Artifacts"
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: "./artifacts"

  publish-packages:
    name: "Publish Packages"
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Download Artifacts"
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: "./artifacts"
      - name: "Install .NET"
        uses: actions/setup-dotnet@v4
      - name: "Publish NuGet Packages"
        run: dotnet nuget push './artifacts/*.nupkg' -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta for cosmosreplication image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            goyalvaibhav/cosmosreplication
            ghcr.io/cosmosreplication/cosmosreplication
      - name: Docker build and push cosmosreplication image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CosmosReplication.Host.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
      - name: Docker meta for cosmosreplication-estimator image
        id: meta-estimator
        uses: docker/metadata-action@v5
        with:
          images: |
            goyalvaibhav/cosmosreplication-estimator
            ghcr.io/cosmosreplication/cosmosreplication-estimator
      - name: Docker build and push cosmosreplication-estimator image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: CosmosReplication.Estimator.Host.Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta-estimator.outputs.tags }}
          labels: ${{ steps.meta-estimator.outputs.labels }}
          annotations: ${{ steps.meta-estimator.outputs.annotations }}
